---
label: default
hide_body: false
is_partial: false
fields:
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: banner
  label: Banner
  type: text
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- type: text
  name: bofas
  label: Bofas
  description: BOFAS AQUI
- type: field_group_list
  name: authors
  label: authors
  fields:
  - type: text
    label: name
    name: name
    description: name
  - type: text
    name: bio
    label: bio
    description: bio
pages:
- content/about.html
- content/test.md
