---
label: services
hide_body: false
is_partial: true
display_field: name
fields:
- type: text
  name: desc
  label: desc
- type: text
  name: name
  label: name
- type: text
  name: cost
  label: cost
